plugins:
  - .yarn/plugins/@yarnpkg/plugin-exec.js
  - .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
  - .yarn/plugins/@yarnpkg/plugin-stage.js
  - .yarn/plugins/@yarnpkg/plugin-typescript.js
  - .yarn/plugins/@yarnpkg/plugin-workspace-tools.js

yarnPath: .yarn/releases/yarn-1.21.1.js
